services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sofomometeorestapi
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    volumes:
      - ./Meteo.Api/appsettings.json:/app/appsettings.json:ro
    env_file:
      - .env 

  db:
    image: postgres:15
    container_name: meteo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - meteo_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: meteo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  meteo_data:
    driver: local
